/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SketchesSplatRouteImport } from './routes/sketches.$'
import { Route as LearnSingularityRouteImport } from './routes/learn.singularity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchesSplatRoute = SketchesSplatRouteImport.update({
  id: '/sketches/$',
  path: '/sketches/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSingularityRoute = LearnSingularityRouteImport.update({
  id: '/learn/singularity',
  path: '/learn/singularity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/singularity': typeof LearnSingularityRoute
  '/sketches/$': typeof SketchesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/singularity': typeof LearnSingularityRoute
  '/sketches/$': typeof SketchesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/singularity': typeof LearnSingularityRoute
  '/sketches/$': typeof SketchesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn/singularity' | '/sketches/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn/singularity' | '/sketches/$'
  id: '__root__' | '/' | '/learn/singularity' | '/sketches/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnSingularityRoute: typeof LearnSingularityRoute
  SketchesSplatRoute: typeof SketchesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketches/$': {
      id: '/sketches/$'
      path: '/sketches/$'
      fullPath: '/sketches/$'
      preLoaderRoute: typeof SketchesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/singularity': {
      id: '/learn/singularity'
      path: '/learn/singularity'
      fullPath: '/learn/singularity'
      preLoaderRoute: typeof LearnSingularityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnSingularityRoute: LearnSingularityRoute,
  SketchesSplatRoute: SketchesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
